/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/AWTForms/Frame.java to edit this template
 */
package fr.ufrsciencestech.panier.view;

import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.awt.event.ActionListener;

/**
 *
 * @author HP
 */
public class VueGAWT extends java.awt.Frame {

    /**
     * Creates new form VueGAWT
     */
    public VueGAWT() {
        initComponents();
        this.desactiverButtonMoins();
        this.addWindowListener(new WindowAdapter(){
            public void windowClosing(WindowEvent e){
                System.exit(0);
            }
        });
        this.pack(); 
        this.setVisible(true);
    }
    
    
    private ActionListener buttonPlusListener;
    private ActionListener buttonMoinsListener;
    
    //pour le clic sur le button plus
    public void addButtonPlusListener(ActionListener listener) {
        this.buttonPlusListener = listener;
    }
    
    public void desactiverButtonPlus (){
        this.Buttonplus.setEnabled(false);
    }
    public void activerButtonPlus (){
        this.Buttonplus.setEnabled(true);
    }
    
    //modification du jlabel compteur
    public void setCompteur(String text) {
        Compteur.setText(text);
    }
    
    //pour le clic sur le button moins
    public void addButtonMoinsListener(ActionListener listener) {
        this.buttonMoinsListener = listener;
    }
    
    public void desactiverButtonMoins (){
        this.Buttonmoins.setEnabled(false);
    }
    public void activerButtonMoins () {
        this.Buttonmoins.setEnabled(true);
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Buttonplus = new java.awt.Button();
        Compteur = new java.awt.Label();
        Buttonmoins = new java.awt.Button();

        setPreferredSize(new java.awt.Dimension(300, 250));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                exitForm(evt);
            }
        });

        Buttonplus.setLabel("+");
        Buttonplus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonplusActionPerformed(evt);
            }
        });
        add(Buttonplus, java.awt.BorderLayout.NORTH);

        Compteur.setAlignment(java.awt.Label.CENTER);
        add(Compteur, java.awt.BorderLayout.CENTER);

        Buttonmoins.setLabel("-");
        Buttonmoins.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonmoinsActionPerformed(evt);
            }
        });
        add(Buttonmoins, java.awt.BorderLayout.SOUTH);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Exit the Application
     */
    private void exitForm(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_exitForm
        System.exit(0);
    }//GEN-LAST:event_exitForm

    private void ButtonplusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonplusActionPerformed
        // TODO add your handling code here:
        if(buttonPlusListener != null) {
            buttonPlusListener.actionPerformed(evt);
        }
    }//GEN-LAST:event_ButtonplusActionPerformed

    private void ButtonmoinsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonmoinsActionPerformed
        // TODO add your handling code here:
        if(buttonMoinsListener != null) {
            buttonMoinsListener.actionPerformed(evt);
        }
    }//GEN-LAST:event_ButtonmoinsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VueGAWT().setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button Buttonmoins;
    private java.awt.Button Buttonplus;
    private java.awt.Label Compteur;
    // End of variables declaration//GEN-END:variables
}
